version: '3.8'

services:
  backend:
    build: .
    container_name: sih_backend_app
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - SECRET_KEY=sih_super_secure_dr_jwt_secret_key_2026
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@timescaledb:5432/sih_db
    depends_on:
      - redis
      - timescaledb
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sih_redis_cache
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: sih_timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sih_db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  timescaledb_data:
